export const states = [
    {label: 'ALABAMA', abbr: 'al', key: 'al'},
    {label: 'ALASKA', abbr: 'ak', key: 'ak'},
    {label: 'ARIZONA', abbr: 'az', key: 'az'},
    {label: 'ARKANSAS', abbr: 'ar', key: 'ar'},
    {label: 'CALIFORNIA', abbr: 'ca', key: 'ca'},
    {label: 'COLORADO', abbr: 'co', key: 'co'},
    {label: 'CONNECTICUT', abbr: 'ct', key: 'ct'},
    {label: 'DELAWARE', abbr: 'de', key: 'de'},
    {label: 'FLORIDA', abbr: 'fl', key: 'fl'},
    {label: 'GEORGIA', abbr: 'ga', key: 'ga'},
    {label: 'HAWAII', abbr: 'hi', key: 'hi'},
    {label: 'IDAHO', abbr: 'id', key: 'id'},
    {label: 'ILLINOIS', abbr: 'il', key: 'il'},
    {label: 'INDIANA', abbr: 'in', key: 'in'},
    {label: 'IOWA', abbr: 'ia', key: 'ia'},
    {label: 'KANSAS', abbr: 'ks', key: 'ks'},
    {label: 'KENTUCKY', abbr: 'ky', key: 'ky'},
    {label: 'LOUISIANA', abbr: 'la', key: 'la'},
    {label: 'MAINE', abbr: 'me', key: 'me'},
    {label: 'MARYLAND', abbr: 'md', key: 'md'},
    {label: 'MASSACHUSETTS', abbr: 'ma', key: 'ma'},
    {label: 'MICHIGAN', abbr: 'mi', key: 'mi'},
    {label: 'MINNESOTA', abbr: 'mn', key: 'mn'},
    {label: 'MISSISSIPPI', abbr: 'ms', key: 'ms'},
    {label: 'MISSOURI', abbr: 'mo', key: 'mo'},
    {label: 'MONTANA', abbr: 'mt', key: 'mt'},
    {label: 'NEBRASKA', abbr: 'ne', key: 'ne'},
    {label: 'NEVADA', abbr: 'nv', key: 'nv'},
    {label: 'NEW HAMPSHIRE', abbr: 'nh', key:  'nh'},
    {label: 'NEW JERSEY', abbr: 'nj', key:  'nj'},
    {label: 'NEW MEXICO', abbr: 'nm', key:  'nm'},
    {label: 'NEW YORK', abbr: 'ny', key:  'ny'},
    {label: 'NORTH CAROLINA', abbr: 'nc', key:  'nc'},
    {label: 'NORTH DAKOTA', abbr: 'nd', key:  'nd'},
    {label: 'OHIO', abbr: 'oh', key: 'oh'},
    {label: 'OKLAHOMA', abbr: 'ok', key: 'ok'},
    {label: 'OREGON', abbr: 'or', key: 'or'},
    {label: 'PENNSYLVANIA', abbr: 'pa', key: 'pa'},
    {label: 'RHODE ISLAND', abbr: 'ri', key:  'ri'},
    {label: 'SOUTH CAROLINA', abbr: 'sc', key:  'sc'},
    {label: 'SOUTH DAKOTA', abbr: 'sd', key:  'sd'},
    {label: 'TENNESSEE', abbr: 'tn', key: 'tn'},
    {label: 'TEXAS', abbr: 'tx', key: 'tx'},
    {label: 'UTAH', abbr: 'ut', key: 'ut'},
    {label: 'VERMONT', abbr: 'vt', key: 'vt'},
    {label: 'VIRGINIA', abbr: 'va', key: 'va'},
    {label: 'WASHINGTON', abbr: 'wa', key: 'wa'},
    {label: 'WEST VIRGINIA', abbr: 'wv', key:  'wv'},
    {label: 'WISCONSIN', abbr: 'wi', key: 'wi'},
    {label: 'WYOMING', abbr: 'wy', key: 'wy'},
  ];


export const feet = [
  {label: '1', key: 1},
  {label: '2', key: 2},
  {label: '3', key: 3},
  {label: '4', key: 4},
  {label: '5', key: 5},
  {label: '6', key: 6},
  {label: '7', key: 7},
  {label: '8', key: 8},
  {label: '9', key: 9},
  {label: '10', key: 10}
];
export const inches = [
  {label: '1', key: 1},
  {label: '2', key: 2},
  {label: '3', key: 3},
  {label: '4', key: 4},
  {label: '5', key: 5},
  {label: '6', key: 6},
  {label: '7', key: 7},
  {label: '8', key: 8},
  {label: '9', key: 9},
  {label: '10', key: 10},
  {label: '11', key: 11} 
];

export const age = [
  {label: '18', key: 1},
  {label: '19', key: 1},
  {label: '21', key: 1},
]